// import type { Metadata } from "next";
// import {
//   Geist,
//   Geist_Mono,
//   Bitcount_Grid_Double,
//   Montserrat,
// } from "next/font/google";
// import { UIProvider } from "../context/UIContext";
// import GlobalModal from "@/components/shared/GlobalModal";
// import Chatbot from "@/components/shared/Chatbot";



// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const bitcountGridDouble = Bitcount_Grid_Double({
//   variable: "--font-bitcount-grid-double",
//   subsets: ["latin"],
// });
// const montserrat = Montserrat({
//   // variable: "--font-montserrat",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: " Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${montserrat.className} ${geistSans.variable} ${geistMono.variable}  antialiased`}
//       >

//       <UIProvider>
//           {children}
//           <GlobalModal /> {/* ✅ Render the modal component here */}
//           <footer/>
//         </UIProvider>

//           {/* <Chatbot /> */}
     
        
//       </body>
//     </html>
//   );
// }

// //  ${geistSans.variable} ${geistMono.variable}






import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import { UIProvider } from "../context/UIContext";
import GlobalModal from "@/components/shared/GlobalModal";
import Chatbot from "@/components/shared/Chatbot";
import FloatingWhatsappButton from "@/components/shared/FloatingWhatsappButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>  
            {/* The Provider must wrap all components that use its context */}
        
          {children}
          
        
    </>
        // {/* The Provider must wrap all components that use its context */}
        // <UIProvider>
        //   {children}
          
        //   <GlobalModal />
          
        //   {/* ✅ Moved Chatbot and FloatingWhatsappButton inside the provider */}
        //   <div className="fixed bottom-5 right-5 z-50 flex flex-col items-end gap-4">
        //     <FloatingWhatsappButton />
        //     <Chatbot />
        //   </div>
        // </UIProvider>
     
  );
}