import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Bitcount_Grid_Double,
  Montserrat,
} from "next/font/google";
import "./globals.css";
import { UIProvider } from "./context/UIContext"; // ✅ Import the UIProvider
import GlobalModal from "@/components/shared/GlobalModal"; // ✅ Import the GlobalModal
import Chatbot from "@/components/shared/Chatbot";
import FloatingWhatsappButton from "@/components/shared/FloatingWhatsappButton"; // ✅ Import the new component
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const bitcountGridDouble = Bitcount_Grid_Double({
  variable: "--font-bitcount-grid-double",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  // variable: "--font-montserrat",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: " Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <UIProvider>
          {children}
          <GlobalModal />
          {/* Floating buttons container: lower z-index, pointer-events-none if property list is open */}
          <div id="floating-buttons-container" className="fixed bottom-5 right-5 z-30 flex flex-col items-end gap-4">
            <FloatingWhatsappButton />
            <Chatbot />
          </div>
        </UIProvider>
      </body>
    </html>
  );
}

// //  ${geistSans.variable} ${geistMono.variable}







// import type { Metadata } from "next";
// import {
//   Geist,
//   Geist_Mono,
//   Bitcount_Grid_Double,
//   Montserrat,
// } from "next/font/google";
// import "./globals.css";
// import { UIProvider } from "./context/UIContext"; // ✅ Import the UIProvider
// import GlobalModal from "@/components/shared/GlobalModal"; // ✅ Import the GlobalModal
// import Chatbot from "@/components/shared/Chatbot";
// import FloatingWhatsappButton from "@/components/shared/FloatingWhatsappButton"; // ✅ Import the new component
// import Link from "next/link";
// import Image from "next/image";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const bitcountGridDouble = Bitcount_Grid_Double({
//   variable: "--font-bitcount-grid-double",
//   subsets: ["latin"],
// });
// const montserrat = Montserrat({
//   // variable: "--font-montserrat",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: " Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${montserrat.className} ${geistSans.variable} ${geistMono.variable}  antialiased`}
//       >

//  {children}
//       </body>
//     </html>
//   );
// }

//  ${geistSans.variable} ${geistMono.variable}
