import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Bitcount_Grid_Double,
  Montserrat,
} from "next/font/google";
import "./globals.css";
import { UIProvider } from "./context/UIContext"; // ✅ Import the UIProvider
import GlobalModal from "@/components/shared/GlobalModal"; // ✅ Import the GlobalModal
import Chatbot from "@/components/shared/Chatbot";
import FloatingWhatsappButton from "@/components/shared/FloatingWhatsappButton"; // ✅ Import the new component
import Link from "next/link";
import Image from "next/image";
import DisclaimerManager from "@/components/shared/DisclaimerManager";
import { FavoritesProvider } from "./context/FavoritesContext"; // ✅ Import the FavoritesProvider
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const bitcountGridDouble = Bitcount_Grid_Double({
  variable: "--font-bitcount-grid-double",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  // variable: "--font-montserrat",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: " Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossOrigin=""
        />
        {/* ✅ MARKER CLUSTER CSS (REQUIRED) */}
        <link
          rel="stylesheet"
          href="https://unpkg.com/react-leaflet-markercluster@3.0.0-rc1/dist/styles.min.css"
        />
          
      </head>
      <body
        className={`${montserrat.className} ${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <UIProvider>
          <FavoritesProvider>
            <Toaster />

            {children}
            <GlobalModal />
            {/* Floating buttons container: lower z-index, pointer-events-none if property list is open */}
            <div
              id="floating-buttons-container"
              className="fixed bottom-5 right-5 z-30 flex flex-col items-end gap-4"
            >
              <FloatingWhatsappButton />
              <Chatbot />
            </div>

            <DisclaimerManager />
          </FavoritesProvider>
        </UIProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import {
//   Geist,
//   Geist_Mono,
//   Bitcount_Grid_Double,
//   Montserrat,
// } from "next/font/google";
// import "./globals.css";
// import { UIProvider } from "./context/UIContext"; // ✅ Import the UIProvider
// import GlobalModal from "@/components/shared/GlobalModal"; // ✅ Import the GlobalModal
// import Chatbot from "@/components/shared/Chatbot";
// import FloatingWhatsappButton from "@/components/shared/FloatingWhatsappButton"; // ✅ Import the new component
// import Link from "next/link";
// import Image from "next/image";
// import DisclaimerManager from "@/components/shared/DisclaimerManager";

// import { AppSidebar } from "@/components/app-sidebar"
// import {
//   Breadcrumb,
//   BreadcrumbItem,
//   BreadcrumbLink,
//   BreadcrumbList,
//   BreadcrumbPage,
//   BreadcrumbSeparator,
// } from "@/components/ui/breadcrumb"
// import { Separator } from "@/components/ui/separator"
// import {
//   SidebarInset,
//   SidebarProvider,
//   SidebarTrigger,
// } from "@/components/ui/sidebar"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const bitcountGridDouble = Bitcount_Grid_Double({
//   variable: "--font-bitcount-grid-double",
//   subsets: ["latin"],
// });
// const montserrat = Montserrat({
//   // variable: "--font-montserrat",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: " Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${montserrat.className} ${geistSans.variable} ${geistMono.variable}  antialiased`}
//       >
//         <SidebarProvider>
//       <AppSidebar />
//       <SidebarInset>

//         <UIProvider>
//           {children}
//           <GlobalModal />
//           {/* Floating buttons container: lower z-index, pointer-events-none if property list is open */}
//           <div
//             id="floating-buttons-container"
//             className="fixed bottom-5 right-5 z-30 flex flex-col items-end gap-4"
//           >
//             <FloatingWhatsappButton />
//             <Chatbot />
//           </div>

//           <DisclaimerManager />
//         </UIProvider>
//       </SidebarInset>
//     </SidebarProvider>
//       </body>
//     </html>
//   );
// }
